### ISSUE TITLE
Edit feature is not working

### ISSUE THREAD

**Issue by abdullah432** [koiralapankaj7/drishya_picker#14]
**Edit feature is not working**
1) After adding text over the image and press "Done", no text appears over an image (shown in attached video).
2) After putting emoji on the image, when press sends, the original file gets return instead of the edited image. 
Note, edited images get saved in phone storage with emojis

https://user-images.githubusercontent.com/48089976/128863951-8824dcb8-8be0-4050-babd-04f61ba454b2.mp4

**Comment by abdullah432** [comment]
Is this issue in your TODO list, how much time it can take?

**Comment by koiralapankaj7** [comment]
Will update this weekend :)

**Comment by koiralapankaj7** [comment]
Fixed in new version.
