### ISSUE TITLE
Image quality is too low after press "Edit" button

### ISSUE THREAD

**Issue by abdullah432** [koiralapankaj7/drishya_picker#18]
When I click the "Edit" button, it looks like the image is out of focus but when I press the "Send" button I get the same quality Image.

It will be nice to provide a parameter to set the quality of an image or return a high-quality image and the developer can compress it later if needed.

**Comment by abdullah432** [comment]
Did you have this in your todos list?

**Comment by koiralapankaj7** [comment]
Yes, maybe next 1 or 2 weeks. I will come with the new version.

**Comment by koiralapankaj7** [comment]
Must have been fixed in the new version. If an issue exists please be free to open it again.
