### ISSUE TITLE
How to listen panel is full screen mode or collapsed mode?

### ISSUE THREAD

**Issue by doanngoctu95** [koiralapankaj7/drishya_picker#19]
Hi @koiralapankaj7 , firstly tks to your contribution about this library, I'm develop app using your lib.
Please help me about this problem: How to listen panel is full screen mode or collapsed mode?

Tks in advance.

**Comment by koiralapankaj7** [comment]
Currently, panel API is private. I will make it public in the next version which might be released in the next 1 or 2 weeks.

**Comment by doanngoctu95** [comment]
okey, I'm waiting for u.

**Comment by koiralapankaj7** [comment]
You can access PanelController which can be found inside GalleryController.
