### ISSUE TITLE
Allowing @ and # Support

### ISSUE THREAD

**Issue by rlee1990** [koiralapankaj7/drishya_picker#25]
It would be nice to bea ble to get access to the view and text controller to add an overlay and other items.

**Comment by koiralapankaj7** [comment]
Where do you want to add overlay? And, Which version you are using?

**Comment by rlee1990** [comment]
@koiralapankaj7 i want to use the overlay when ever you are typing. I am using dev 2.0

**Comment by rlee1990** [comment]
@koiralapankaj7 also are we able to load our own fonts?
